
const Detail = [{
    id:1,
    icon:"/images/messageBox.png",
    image: "../images/browser-stats.svg",
    title: "Manage Enquiries",
},
{   id:2,
    icon:"/images/client.png",
    image: "../images/11.webp",
    title: "Manage Clients",
},
{   id:3,
    icon:"/images/check.png",
    image: "../images/12.png",
    title: "Manage Quotation",
},
{   id:4,
    icon:"/images/invoice.png",
  image: "../images/13.png",
    title: "Manage Invoice",
},
{   id:5,
    icon:"/images/remainder.png",
    image: "../images/14.jpg",
    title: "Manage Reminder",
},
{   id:6,
    icon:"/images/complaint.png",
    image: "../images/15.jpg",
    title: "Manage Complaints",
},
{   id:7,
    icon:"/images/report.png",
    image: "../images/16.png",
    title: "Manage Enquiry Report",
},
{   id:8,
    icon:"/images/support.png",
    image: "../images/17.jpg",
    title: "Manage Call Support",
},
{   id:9,
    icon:"/images/camp.png",
    image: "../images/18.jpg",
    title: "Manage Project Camp",
},



]
export default Detail;